### ISSUE TITLE
Cameras uptime analysis on CI

### ISSUE THREAD

**Issue by Drusy** [Drusy/auvergne-webcams-ios#15]

**Comment by ol-v-er** [comment]
ça va servir à quoi d'avoir cette information?

**Comment by Drusy** [comment]
Let us know when a camera is down, understand why, and fix it

Scenario:
JSON configuration file -> App -> Cameras display
JSON configuration file -> CI -> Cameras status

**Comment by Drusy** [comment]
Openium CI
