### ISSUE TITLE
Too much zoom level on camera live

### ISSUE THREAD

**Issue by ol-v-er** [Drusy/auvergne-webcams-ios#23]
There is too many zoom level in the camera live.

I think there should be only two level. Zoom and Full width. Like in the iOS Photo app.

**Comment by Drusy** [comment]
Fixed by 4dbe080798cb3bd97c832f1811ae51ef1f19322e
@ol-v-er let me know if the feeling is better using the app. I also improve the zoom offset. If you double tap on the right of the image, the zoom will be centered on the tap region.
