### ISSUE TITLE
Display last update

### ISSUE THREAD

**Issue by Drusy** [Drusy/auvergne-webcams-ios#3]
Display last webcam update.
Also notify user of an offline usage of the app.

**Comment by ol-v-er** [comment]
For now it displays the hour of last download of the image. Not the hour of the last update of the picture sent by the Webcam.

**Comment by Drusy** [comment]
Yes, that's partly why this issue is not closed yet :)
Actually I don't know precisely where to get this information... Any idea ? Have to check in the metadata of the JPG images @ol-v-er would you have some time to check it ?

**Comment by ol-v-er** [comment]
Maybe the HTTP Header Last-Modified can do the trick.

For example with this url http://srv02.trinum.com/ibox/ftpcam/1280_lioran_station.jpg, the last modified is :
Last-Modified:Wed, 22 Feb 2017 07:45:37 GMT
And the hour of the server is : 
Date:Wed, 22 Feb 2017 07:56:05 GMT

I still need the check if it's reliable nightly.

**Comment by Drusy** [comment]
Seems reliable, let's try this

> Date:Thu, 23 Feb 2017 19:57:30 GMT
> ETag:"b68d4a5cf78dd21:0"
> Last-Modified:Thu, 23 Feb 2017 17:07:49 GMT

**Comment by Drusy** [comment]
LGTM e0ff4759f590d9f0829d653543a52a20d0d2419f
