### ISSUE TITLE
Le webcam category title is truncated

### ISSUE THREAD

**Issue by ol-v-er** [Drusy/auvergne-webcams-ios#33]
On traffic cameras on a 4" screen, the title does not fit. Even if there is available space

![img_0077](https://cloud.githubusercontent.com/assets/724538/24010444/33e7cce8-0a78-11e7-8157-7485d953695e.PNG)

**Comment by Drusy** [comment]
Fixed by 886efa8, do not hesitate to re-open the issues if you find some section title issue in the next Testflight (v1.1.1).
