### ISSUE TITLE
Add open sources dependencies names/licences listing

### ISSUE THREAD

**Issue by kenji21** [Drusy/auvergne-webcams-ios#43]
In respect to work made by community, we should display all dependencies names / licenses.

Maybe from the "À propos" page, then a list / then licence details ?

**Comment by Drusy** [comment]
Could worth a look: https://github.com/mono0926/LicensePlist/blob/master/README.md

**Comment by Drusy** [comment]
Detail of these could be shown this way https://github.com/keitaoouchi/MarkdownView?utm_campaign=iOS%2BDev%2BWeekly&utm_medium=email&utm_source=iOS_Dev_Weekly_Issue_302

**Comment by Drusy** [comment]
Done in 7ecaabe
