### ISSUE TITLE
List of sections is not scrolling smoothly

### ISSUE THREAD

**Issue by SkyleKayma** [Drusy/auvergne-webcams-ios#57]
The list of the sections ( the one which is scrolling vertically ) isnot really smooth. It seems to take some time to redraw the component that is scrolling horizontally. 
On Iphone 5S, it's a little bit disturbing.

**Comment by Drusy** [comment]
Imrpoved by List of sections is not scrolling smoothly #57 but still not perfect

**Comment by Drusy** [comment]
Cannot afford this issue in a reasonable development time... Perf seems to be fine since iPhone6S / iPhone SE
